module.exports = [
    "Abaddon",
    "Algos",
    "Apocalypse",
    "Apocalypse Navy Issue",
    "Arbitrator",
    "Armageddon",
    "Armageddon Navy Issue",
    "Ashimmu",
    "Astero",
    "Atron",
    "Augoror",
    "Augoror Navy Issue",
    "Badger",
    "Bantam",
    "Barghest",
    "Bellicose",
    "Bestower",
    "Bhaalgorn",
    "Blackbird",
    "Breacher",
    "Brutix",
    "Brutix Navy Issue",
    "Burst",
    "Caldari Navy Hookbill",
    "Caracal",
    "Caracal Navy Issue",
    "Catalyst",
    "Celestis",
    "Coercer",
    "Condor",
    "Corax",
    "Cormorant",
    "Covetor",
    "Crucifier",
    "Crucifier Navy Issue",
    "Cruor",
    "Cyclone",
    "Cyclone Fleet Issue",
    "Cynabal",
    "Damavik",
    "Daredevil",
    "Dominix",
    "Dominix Navy Issue",
    "Dragoon",
    "Drake",
    "Drake Navy Issue",
    "Dramiel",
    "Drekavac",
    "Echelon",
    "Epithal",
    "Executioner",
    "Exequror",
    "Exequror Navy Issue",
    "Federation Navy Comet",
    "Ferox",
    "Ferox Navy Issue",
    "Garmur",
    "Gila",
    "Gnosis",
    "Griffin",
    "Griffin Navy Issue",
    "Harbinger",
    "Harbinger Navy Issue",
    "Heron",
    "Heron Navy Issue",
    "Hoarder",
    "Hurricane",
    "Hurricane Fleet Issue",
    "Hyperion",
    "Imicus",
    "Imicus Navy Issue",
    "Imperial Navy Slicer",
    "Incursus",
    "Inquisitor",
    "Iteron Mark V",
    "Kestrel",
    "Kikimora",
    "Kryos",
    "Leshak",
    "Machariel",
    "Maelstrom",
    "Magnate",
    "Magnate Navy Issue",
    "Maller",
    "Mammoth",
    "Maulus",
    "Maulus Navy Issue",
    "Megathron",
    "Megathron Navy Issue",
    "Merlin",
    "Miasmos",
    "Moa",
    "Myrmidon",
    "Myrmidon Navy Issue",
    "Naga",
    "Navitas",
    "Nereus",
    "Nestor",
    "Nightmare",
    "Noctis",
    "Omen",
    "Omen Navy Issue",
    "Oracle",
    "Orca",
    "Orthrus",
    "Osprey",
    "Osprey Navy Issue",
    "Phantasm",
    "Porpoise",
    "Praxis",
    "Probe",
    "Probe Fleet Issue",
    "Procurer",
    "Prophecy",
    "Prophecy Navy Issue",
    "Punisher",
    "Rattlesnake",
    "Raven",
    "Raven Navy Issue",
    "Republic Fleet Firetail",
    "Retriever",
    "Rifter",
    "Rodiva",
    "Rokh",
    "Rupture",
    "Scorpion",
    "Scorpion Navy Issue",
    "Scythe",
    "Scythe Fleet Issue",
    "Sigil",
    "Skybreaker",
    "Slasher",
    "Stabber",
    "Stabber Fleet Issue",
    "Stormbringer",
    "Stratios",
    "Succubus",
    "Sunesis",
    "Talos",
    "Talwar",
    "Tayra",
    "Tempest",
    "Tempest Fleet Issue",
    "Thorax",
    "Thunderchild",
    "Thrasher",
    "Tormentor",
    "Tornado",
    "Tristan",
    "Typhoon",
    "Typhoon Fleet Issue",
    "Vedmak",
    "Venture",
    "Vexor",
    "Vexor Navy Issue",
    "Victorieux Luxury Yacht",
    "Vigil",
    "Vigil Fleet Issue",
    "Vigilant",
    "Vindicator",
    "Worm",
    "Wreathe",
    ]